# USUÁRIOS

### # Listar usuários
GET http://localhost:3000/users

### # Criar novo usuário
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Lucas Fernandes",
  "sex": "Masculino",
  "address": "Rua B, 213",
  "birthDate": "1990-04-13T15:32:00.000Z"
}



# AUTORES

### # Listar autores
GET http://localhost:3000/authors

### # Criar novo autor
POST http://localhost:3000/authors
Content-Type: application/json


{
  "name": "George R. R. Martin",
  "birthDate": "1948-09-20",
  "sex": "Masculino",
  "writingGenre": "Fantasy"
}



# LIVROS

### # Listar livros
GET http://localhost:3000/books

### # Criar novo livro
POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "A Game of Thrones",
  "synopsis": "O início da saga épica de Westeros, onde casas nobres lutam pelo Trono de Ferro e segredos sombrios ameaçam o reino.",
  "author": "George R. R. Martin",
  "year": 1996,
  "isAvailable": true,
  "expectedReturnDate": null
}


# EMPRÉSTIMOS

### # Criar novo empréstimo
POST http://localhost:3000/loans
Content-Type: application/json

{
  "user": "Lucas Fernandes",
  "book": "A Game of Thrones",
  "loanDate": "2025-10-26T10:00:00.000Z",
  "returnDate": "2025-10-29T10:00:00.000Z"
}